export interface City {
  value: string;
  label: string;
  region?: string;
}

export function getCities(): City[] {
  return [
    { value: 'jakarta', label: 'Jakarta' },
    { value: 'surabaya', label: 'Surabaya' },
    { value: 'bekasi', label: 'Bekasi' },
    { value: 'bandung', label: 'Bandung' },
    { value: 'medan', label: 'Medan' },
    { value: 'depok', label: 'Depok' },
    { value: 'tangerang', label: 'Tangerang' },
    { value: 'palembang', label: 'Palembang' },
    { value: 'semarang', label: 'Semarang' },
    { value: 'makassar', label: 'Makassar' },
    { value: 'south tangerang', label: 'South Tangerang' },
    { value: 'batam', label: 'Batam' },
    { value: 'pekanbaru', label: 'Pekanbaru' },
    { value: 'bandar lampung', label: 'Bandar Lampung' },
    { value: 'padang', label: 'Padang' },
    { value: 'samarinda', label: 'Samarinda' },
    { value: 'malang', label: 'Malang' },
    { value: 'tasikmalaya', label: 'Tasikmalaya' },
    { value: 'serang', label: 'Serang' },
    { value: 'balikpapan', label: 'Balikpapan' },
    { value: 'banjarmasin', label: 'Banjarmasin' },
    { value: 'pontianak', label: 'Pontianak' },
    { value: 'denpasar', label: 'Denpasar' },
    { value: 'jambi', label: 'Jambi' },
    { value: 'cimahi', label: 'Cimahi' },
    { value: 'surakarta', label: 'Surakarta' },
    { value: 'kupang', label: 'Kupang' },
    { value: 'manado', label: 'Manado' },
    { value: 'cilegon', label: 'Cilegon' },
    { value: 'mataram', label: 'Mataram' },
    { value: 'jayapura', label: 'Jayapura' },
    { value: 'bengkulu', label: 'Bengkulu' },
    { value: 'palu', label: 'Palu' },
    { value: 'yogyakarta', label: 'Yogyakarta' },
    { value: 'sukabumi', label: 'Sukabumi' },
    { value: 'ambon', label: 'Ambon' },
    { value: 'kendari', label: 'Kendari' },
    { value: 'cirebon', label: 'Cirebon' },
    { value: 'dumai', label: 'Dumai' },
    { value: 'pekalongan', label: 'Pekalongan' },
    { value: 'palangka raya', label: 'Palangka Raya' },
    { value: 'binjai', label: 'Binjai' },
    { value: 'kediri', label: 'Kediri' },
    { value: 'sorong', label: 'Sorong' },
    { value: 'pematangsiantar', label: 'Pematangsiantar' },
    { value: 'banjarbaru', label: 'Banjarbaru' },
    { value: 'tegal', label: 'Tegal' },
    { value: 'banda aceh', label: 'Banda Aceh' },
    { value: 'tarakan', label: 'Tarakan' },
    { value: 'probolinggo', label: 'Probolinggo' },
    { value: 'singkawang', label: 'Singkawang' },
    { value: 'lubuklinggau', label: 'Lubuklinggau' },
    { value: 'padang sidempuan', label: 'Padang Sidempuan' },
    { value: 'tanjungpinang', label: 'Tanjungpinang' },
    { value: 'bitung', label: 'Bitung' },
    { value: 'pangkalpinang', label: 'Pangkalpinang' },
    { value: 'batu', label: 'Batu' },
    { value: 'pasuruan', label: 'Pasuruan' },
    { value: 'banjar', label: 'Banjar' },
    { value: 'gorontalo', label: 'Gorontalo' },
    { value: 'ternate', label: 'Ternate' },
    { value: 'madiun', label: 'Madiun' },
    { value: 'salatiga', label: 'Salatiga' },
    { value: 'prabumulih', label: 'Prabumulih' },
    { value: 'lhokseumawe', label: 'Lhokseumawe' },
    { value: 'langsa', label: 'Langsa' },
    { value: 'botang', label: 'Bontang' },
    { value: 'tanjungbalai', label: 'Tanjungbalai' },
    { value: 'tebing tinggi', label: 'Tebing Tinggi' },
    { value: 'metro', label: 'Metro' },
    { value: 'palopo', label: 'Palopo' },
    { value: 'bima', label: 'Bima' },
    { value: 'baubau', label: 'Baubau' },
    { value: 'parepare', label: 'Parepare' },
    { value: 'blitar', label: 'Blitar' },
    { value: 'pagar alam', label: 'Pagar Alam' },
    { value: 'payakumbuh', label: 'Payakumbuh' },
    { value: 'gunungsitoli', label: 'Gunungsitoli' },
    { value: 'mojokerto', label: 'Mojokerto' },
    { value: 'bukittinggi', label: 'Bukittinggi' },
    { value: 'kotamobagu', label: 'Kotamobagu' },
    { value: 'magelang', label: 'Magelang' },
    { value: 'tidore islands', label: 'Tidore Islands' },
    { value: 'tomohon', label: 'Tomohon' },
    { value: 'sungai penuh', label: 'Sungai Penuh' },
    { value: 'subulussalam', label: 'Subulussalam' },
    { value: 'pariaman', label: 'Pariaman' },
    { value: 'sibolga', label: 'Sibolga' },
    { value: 'tual', label: 'Tual' },
    { value: 'solok', label: 'Solok' },
    { value: 'sawahlunto', label: 'Sawahlunto' },
    { value: 'padang panjang', label: 'Padang Panjang' },
    { value: 'sabang', label: 'Sabang' },
  ];
}

export function getCitiesByRegion(region: string): City[] {
  const allCities = getCities();
  return allCities.filter((city) => city.region === region);
}
